<?php
declare(strict_types=1);
require_once __DIR__ . '/../app/config/config.php';
require_once __DIR__ . '/../app/core/helpers.php';
require_once __DIR__ . '/../app/core/admin_guard.php';
require_once __DIR__ . '/../app/config/database.php';
$series=db()->query('SELECT id,title FROM series ORDER BY title')->fetchAll(); $id=(int)($_GET['id']??0); $stmt=db()->prepare('SELECT * FROM episodes WHERE id=:id LIMIT 1'); $stmt->execute(['id'=>$id]); $item=$stmt->fetch(); if(!$item){redirect('episodes-list.php');}
if($_SERVER['REQUEST_METHOD']==='POST'){db()->prepare('UPDATE episodes SET series_id=:series_id, season_number=:season_number, episode_number=:episode_number, title=:title, description=:description, duration_min=:duration_min, air_date=:air_date, thumbnail_url=:thumbnail_url WHERE id=:id')->execute(['id'=>$id,'series_id'=>(int)$_POST['series_id'],'season_number'=>(int)$_POST['season_number'],'episode_number'=>(int)$_POST['episode_number'],'title'=>$_POST['title'],'description'=>$_POST['description'],'duration_min'=>(int)$_POST['duration_min'],'air_date'=>$_POST['air_date']?:null,'thumbnail_url'=>$_POST['thumbnail_url']]); flash('success','Episode updated.'); redirect('episodes-list.php');}
require_once __DIR__ . '/../app/views/partials/header.php'; require_once __DIR__ . '/../app/views/partials/navbar.php'; ?><main class="container narrow"><h1>Edit Episode</h1><form method="post" class="card form-grid"><select name="series_id" required><?php foreach($series as $s): ?><option value="<?= (int)$s['id'] ?>" <?= ((int)$item['series_id']===(int)$s['id'])?'selected':'' ?>><?= e($s['title']) ?></option><?php endforeach; ?></select><input name="season_number" type="number" value="<?= e((string)$item['season_number']) ?>" required><input name="episode_number" type="number" value="<?= e((string)$item['episode_number']) ?>" required><input name="title" value="<?= e($item['title']) ?>" required><textarea name="description"><?= e((string)$item['description']) ?></textarea><input name="duration_min" type="number" value="<?= e((string)$item['duration_min']) ?>" required><input name="air_date" type="date" value="<?= e((string)($item['air_date'] ?? '')) ?>"><input name="thumbnail_url" value="<?= e((string)($item['thumbnail_url'] ?? '')) ?>"><button type="submit">Update</button></form></main><?php require_once __DIR__ . '/../app/views/partials/footer.php'; ?>
